# ---------- BUILD STAGE ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY ingestion/go.mod ingestion/go.sum ./
RUN go mod download

COPY ingestion/ .

RUN go build -o service

# ---------- RUN STAGE ----------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service .

EXPOSE 8002

CMD ["./service"]