# ---------- BUILD STAGE ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY auth/go.mod auth/go.sum ./
RUN go mod download

COPY auth/ .

RUN go build -o service

# ---------- RUN STAGE ----------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service .

EXPOSE 8001

CMD ["./service"]