# ---------- BUILD STAGE ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

# copy go modules from management folder
COPY management/go.mod management/go.sum ./
RUN go mod download

# copy service source
COPY management/ .



RUN go build -o service

# ---------- RUN STAGE ----------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service .

EXPOSE 8004

CMD ["./service"]