# ---------- BUILD STAGE ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY question/go.mod question/go.sum ./
RUN go mod download

COPY question/ .

RUN go build -o service

# ---------- RUN STAGE ----------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service .

EXPOSE 8005

CMD ["./service"]